steps:
  # ====BUILD====
  # docker build --tag gcr.io/your-project-id/your-repository-name-test.
  - name: 'docker'
    args:
      [
        'build',
        '--tag=${_CONTAINER_REGISTRY}/$REPO_NAME-test',
	'--cache-from','${_CONTAINER_REGISTRY}/$REPO_NAME:latest',
        '.',
      ]

  # docker push gcr.io/your-project-id/your-repository-name-test
  - name: 'docker'
    args: ['push', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # =============

  # lastest and push
  # pull test
  - name: 'docker'
    args: ['pull', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # push it back and tag lastest  
  - name: 'docker'
    args: 
      [
        'tag',
        '${_CONTAINER_REGISTRY}/$REPO_NAME-test',
        '${_CONTAINER_REGISTRY}/$REPO_NAME:latest'
      ] 

  - name: 'docker'
    args: ['push', '${_CONTAINER_REGISTRY}/$REPO_NAME']
images: ['${_CONTAINER_REGISTRY}/$REPO_NAME']
 
