steps:
  # ====BUILD====

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull ${_CONTAINER_REGISTRY}/$REPO_NAME:latest || exit 0'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 
            'build',
            '-t','${_CONTAINER_REGISTRY}/$REPO_NAME-test',
            '--cache-from','${_CONTAINER_REGISTRY}/$REPO_NAME:latest',
            '.'     
  
  # =============

  # lastest and push
  # pull test
  - name: 'docker'
    args: ['pull', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # push it back and tag lastest  
  - name: 'bash'
    args:
      - -c 
      - |-
         if ($TAG_NAME); then
           IMAGE=${_CONTAINER_REGISTRY}/$REPO_NAME-test:$TAG_NAME
         else
           IMAGE=${_CONTAINER_REGISTRY}/$REPO_NAME-test:latest
         fi

         docker tag ${_CONTAINER_REGISTRY}/$REPO_NAME-test $IMAGE
         docker push $IMAGE
images: ['${_CONTAINER_REGISTRY}/$REPO_NAME',
         '${_CONTAINER_REGISTRY}/$REPO_NAME:latest',
         '${_CONTAINER_REGISTRY}/$REPO_NAME-test']
