steps:
  # ====BUILD====
  # docker build --tag gcr.io/your-project-id/your-repository-name-test.
  - name: 'docker'
    args:
      [
        'build',
        '--tag=${_CONTAINER_REGISTRY}/$REPO_NAME-test',
        '.',
      ]

  # docker push gcr.io/your-project-id/your-repository-name-test
  - name: 'docker'
    args: ['push', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # =============

  # lastest and push
  # pull test    branches: ['develop', 'qas']
  - name: 'docker'
    args: ['pull', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # tag normal
  - name: 'docker'
    args: ['tag', '${_CONTAINER_REGISTRY}/$REPO_NAME-test','${_CONTAINER_REGISTRY}/$IMAGE:$TAG_NAME']

  # push it back 
  - name: 'docker'
    args: ['push', '${_CONTAINER_REGISTRY}/$IMAGE:$TAG_NAME']
images: ['${_CONTAINER_REGISTRY}/$REPO_NAME:$TAG_NAME']
 
