steps:
  # ====BUILD====
  # docker build --tag gcr.io/your-project-id/your-repository-name:your-tag .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--tag=${_CONTAINER_REGISTRY}/$REPO_NAME-test',
        '.',
      ]

  # docker push gcr.io/your-project-id/your-repository-name:your-tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # =============

  # lastest and push
  # pull test
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # tag normal
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '${_CONTAINER_REGISTRY}/$REPO_NAME-test','${_CONTAINER_REGISTRY}/$IMAGE:$TAG_NAME']

  # push it back 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_CONTAINER_REGISTRY}/$IMAGE:$TAG_NAME']

 
