steps:
  # ====BUILD====
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_CONTAINER_REGISTRY}/$REPO_NAME || exit 0']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t', '${_CONTAINER_REGISTRY}/$REPO_NAME-test',
            '--cache-from', '${_CONTAINER_REGISTRY}/$REPO_NAME',
            '.'
        ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','${_CONTAINER_REGISTRY}/$REPO_NAME-test']  
  # =============

  # test and push
  # pull test
  - name: 'docker'
    args: ['pull', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  - name: 'docker'
    args: ['push', '${_CONTAINER_REGISTRY}/$REPO_NAME' ]
  
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        '-n',
        '${_NAMESPACE}-qas',
        'image',
        'deployment',
        '$REPO_NAME',
        '$REPO_NAME=${_CONTAINER_REGISTRY}/$REPO_NAME',
      ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=c-5l94t'
   
 images: ['${_CONTAINER_REGISTRY}/$REPO_NAME',
         '${_CONTAINER_REGISTRY}/$REPO_NAME:latest',
         
