steps:
  # ====BUILD====
  # docker build --tag gcr.io/your-project-id/your-repository-name-test.
  - name: 'docker'
    args:
      [
        'build',
        '--tag=${_CONTAINER_REGISTRY}/$REPO_NAME-test',
	'--cache-from','${_CONTAINER_REGISTRY}/$REPO_NAME:latest',
        '.',
      ]

  # docker push gcr.io/your-project-id/your-repository-name-test
  - name: 'docker'
    args: ['push', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # =============

  # lastest and push
  # pull test
  - name: 'docker'
    args: ['pull', '${_CONTAINER_REGISTRY}/$REPO_NAME-test']

  # push it back and tag lastest  
  - name: 'bash'
    args:
      - -c 
      - |-
         if ($TAG_NAME); then
           IMAGE=${_CONTAINER_REGISTRY}/$REPO_NAME-test:$TAG_NAME
         else
           IMAGE=${_CONTAINER_REGISTRY}/$REPO_NAME-test:latest
         fi

         docker tag ${_CONTAINER_REGISTRY}/$REPO_NAME-test $IMAGE
         docker push $IMAGE
images: ['${_CONTAINER_REGISTRY}/$REPO_NAME']
