export const MESSAGE = {
  1: "Login Successfully.",
  2: "Server is unavailable. Please contact system administrator.",
  3: "Internal server error, Please try again or contact Administrator.",
  4: "Please fill out this field.",
  5: "Password must contain at least 6 characters.",
  6: "Your password has been changed (from front-end)",
  7: "Error Please Contact Admin (from front-end)",
  8: "Please specify email address.",
  9: "Incorrect email format. Please specify email with the correct format.",
  10: "Please enter a valid email address.",
  11: "Email has been Sent (from front-end)",
  12: "Error Please Contact Admin (from front-end)",
  13: "Welcome to Admin panel.",
  14: "Do you want to delete Job Description ?",
  15: "Delete Job Description successfully.",
  16: "Delete Job Description failed.",
  17: "by pressing ESC",
  18: "by clicking on a backdrop",
  19: "Delete Job Request successfully.",
  20: "Delete Job Request failed.",
  21: "Do you want to confirm job request?",
  22: "Do you want to delete job request?",
  23: "Approve Job Request successfully.",
  24: "Approve Job Request failed.",
  25: "Reject Job Request successfully.",
  26: "Fail to reject the job request.",
  27: "Get JD Failed",
  28: "Error with Method Success",
  29: "Do you want to save job request?",
  30: "Capacity must be greater than 0.",
  31: "Do you want to go back?",
  32: "Start date must be before end date.",
  33: "Invalid date format. (Please enter dd/mm/yyyy)",
  34: "Please specify start date and end date.",
  35: "Update Successfully",
  36: "Update Failed.",
  37: "Create Successfully.",
  38: "Create Failed.",
  39: "Do you want to buy CV?",
  40: "Do you want to buy CV and send to payroll?",
  41: "Do you want to send to payroll?",
  42: "Do you want to send an email to request for missing information?",
  43: "Do you want to Reject?",
  44: "Do you want to revoke?",
  45: "Do you want to send to HR?",
  46: "Do you want to send email to candidate and pass to exam?",
  47: "Do you confirm that this candidate pass to appointment ?",
  48: "Do you want to submit?",
  49: "Do you want to exit this page ?",
  50: "Please specify password (minimum of 6 characters)",
  51: "Please enter the username.",
  52: "Forgot password?",
  53: "Please complete all required fields.",
  54: "Do you want to save job description?",
  55: "The total percentage must not exceed 100%",
  56: "Total percentage must equal to 100%",
  57: "Confirmation password is not identical.",
  58: "Please enter work experience details.",
  59: "Please enter password.",
  60: "Please enter confirmation password.",
  61: "Do you want to go back?",
  62: 'Please enter "From" value less than "To" value.',
  63: "% of work experience must be greater than 0%",
  64: "% of work experience should not be less than the maximum value of work experience detail.",
  65: "The value is discontinuous. Please recheck the range (From - To).",
  66: "% of education should not be less than the maximum value of education detail.",
  67: "% Of study must not be equal to 0% of all degrees.",
  68: "Please enter education details.",
  69: "A summary of all hard skills (%) you've entered must be equal to calculated " +
    '"Total Hard Skill (%)"',
  70: "Please enter hard skill details.",
  71: "% of work experience should not be less than the maximum value of work experience detail.",
  72: "The value of the hard skill must not duplicate. Please try again.",
  73: "% of hard skill must be greater than 0%",
  74: "A summary of all soft skills (%) you've entered must be equal to calculated " +
    '"Total Soft Skill (%)"',
  75: "Please enter soft skill details.",
  76: "The value of the soft skill must not duplicate. Please try again.",
  77: "% of soft skill must be greater than 0%",
  78: "A summary of all certificate (%) you've entered must be equal to calculated " +
    '"Total Certificate (%)"',
  79: "Please enter certificate details.",
  80: "The value of the certificate must not duplicate. Please try again.",
  81: "% of certificate must be greater than 0%",
  82: "Update Successfully.",
  83: "Update Failed.",
  84: "Create Successfully.",
  85: "Create Failed.",
  86: "% of Work experience must not exceed #1 %",
  87: "% of Education must not exceed #1 %",
  88: "A summary of all hard skills (%) you'" +
    "ve entered must be equal to calculated " +
    '"Total Hard Skill (#1%)"',
  89: "A summary of all soft skills (%) you'" +
    "ve entered must be equal to calculated " +
    '"Total Soft Skill (#1%)"',
  90: "A summary of all certificate (%) you'" +
    "ve entered must be equal to calculated " +
    '"Total Certificate (#1%)"',
  91: "Invalid date format. (Please enter dd/mm/yyyy)",
  92: "Invalid time format. (Please enter hh:mm)",
  93: "Confirmation password is not identical.",
  94: "Your new password must not be the same as the current password.",
  95: "Date From must be before Date To.",
  96: "Please enter new password.",
  97: "Please enter firstname.",
  98: "Please enter lastname.",
  99: "Do you want to save change?",
  100: 'Do you want to send candidate to status "Pending exam score"?',
  101: "Do you want to revoke?",
  102: "Please enter available date or after sign contract (day).",
  103: "Do you want to send candidates to HR for an interview?",
  104: "Do you want to send email to candidate and pass to interview?",
  105: "Please enter date from less than date to.",
  106: "Time From must be before Time To.",
  107: "Please select a location.",
  108: 'Do you want to send candidate to status "Pending interview score"?',
  109: 'Do you want to send candidate to status "Pending sign contract"?',
  110: 'Do you want to send email to candidate?',
  111: 'Do you want to send candidate to onboard?',
  112: 'Please enter sign contract date.',
  113: 'Please enter sign contract time.',
  114: 'Please input agree start date.',
  115: 'Do you want to send candidate to Job Started?',
  116: 'Please enter a valid date.',
  117: 'This candidate is found in', // EXAM
  118: 'This candidate is found in', // APPOINTMENT
  119: 'Do you want to send candidates to status "Pending sign contract"?',
  120: 'Do you want to cancel change?',
  121: 'The specified file is larger than the maximum supported file size. (10MB)',
  122: 'At least one record must be equal to max value',
  123: 'Do you want to delete Job Position [Master] ?',
  124: 'Do you want to save Job Position [Master] ?',
  125: 'Please input start date.',
  126: 'Please input expiry date.',
  127: 'Please input internal password.',
  128: 'Please input external password.',
  129: 'Please input password.',
  130: 'Please specify password (initial)',
  131: 'Please input Gmail  password.',
  132: 'Please input Jobsdb password.',
  133: "Do you want to save template?",
  134: "Do you want to save application form?",
  135: "Please specify onboard date.",
  136: "Please select email type.",
  137: "Please enter job position",
  138: "Please enter keyword",
  139: "Please select email.",
  140: "Please select Department.",
  141: "Please select Job Position.",
  142: "Please input onboard date.",
};
